on: [ push ]
name: Install
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Go Get Check
          uses: joshcarp/gogetcheck@v0.6.0
          with:
            package: github.com/joshcarp/dmt/pkg/dmt
